In [1]:
import torch 
import torch.nn as nn

In [2]:
train_data = "i need to study ai"

word_set = set(train_data.split())

vocab = {word: i+2 for i, word in enumerate(word_set)}
vocab["<unk>"] = 0
vocab["<pad>"] = 1
print(vocab)

{'need': 2, 'study': 3, 'i': 4, 'to': 5, 'ai': 6, '<unk>': 0, '<pad>': 1}


In [3]:
embedding_table = torch.FloatTensor([
                               [ 0.0,  0.0,  0.0],
                               [ 0.0,  0.0,  0.0],
                               [ 0.2,  0.9,  0.3],
                               [ 0.1,  0.5,  0.7],
                               [ 0.2,  0.1,  0.8],
                               [ 0.4,  0.1,  0.1],
                               [ 0.1,  0.8,  0.9],
                               [ 0.6,  0.1,  0.1]])

In [5]:
target_length = 10
sample = "i am happy".split()

idxes = []

for word in sample:
    try:
        integer_index = vocab[word]
        idxes.append(integer_index)
    except KeyError:
        idxes.append(vocab["<unk>"])

if len(idxes) < target_length:
    idxes += [vocab["<pad>"]] * (target_length - len(idxes))

lookup_result = embedding_table[idxes,: ]
print(lookup_result)

tensor([[0.2000, 0.1000, 0.8000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [7]:
embedding_layer = nn.Embedding(num_embeddings=len(vocab), embedding_dim=3, padding_idx=1)

print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.4962, -0.7470, -0.6623],
        [ 0.0000,  0.0000,  0.0000],
        [-1.4584, -0.5342,  0.7229],
        [-0.6700, -1.5769, -0.4638],
        [ 0.1713, -1.2730, -0.5072],
        [ 1.3171,  0.2763,  0.3708],
        [ 0.3459,  1.4808,  1.5153]], requires_grad=True)


In [18]:
embedding_layer(torch.tensor([0, 1, 2, 3, 4, 1, 2, 2]))

tensor([[ 0.4962, -0.7470, -0.6623],
        [ 0.0000,  0.0000,  0.0000],
        [-1.4584, -0.5342,  0.7229],
        [-0.6700, -1.5769, -0.4638],
        [ 0.1713, -1.2730, -0.5072],
        [ 0.0000,  0.0000,  0.0000],
        [-1.4584, -0.5342,  0.7229],
        [-1.4584, -0.5342,  0.7229]], grad_fn=<EmbeddingBackward0>)